#!/usr/bin/python3.9

import sys

from http.server import SimpleHTTPRequestHandler
import socketserver

class MyHTTPRequestHandler( SimpleHTTPRequestHandler ):
	def end_headers( self ):
		self.send_my_headers()
		SimpleHTTPRequestHandler.end_headers( self )
		# server.SimpleHTTPRequestHandler.end_headers( self )

	def send_my_headers(self):
		self.send_header( "Cache-Control", "no-cache, no-store, must-revalidate" )
		self.send_header( "Pragma", "no-cache" )
		self.send_header( "Expires", "0" )

port = int( sys.argv[ 1 ] )
with socketserver.TCPServer( ( "", port ), MyHTTPRequestHandler ) as httpd:
	print( "serving at port: ", port )
	httpd.serve_forever()

